# Generated by Django A.B on YYYY-MM-DD HH:MM
from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    OnlineCoupons = apps.get_model('users', 'OnlineCoupons')
    for row in OnlineCoupons.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0006_add_uuid_field'),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]

