# Generated by Django 4.1 on 2022-09-15 19:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0005_remove_volunteers_approved_volunteers_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteers',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='volunteers',
            name='registerDate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
