# Generated by Django 4.1 on 2022-09-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0010_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='outlet',
            field=models.CharField(default='', max_length=255),
        ),
    ]
