# Generated by Django 4.1 on 2022-09-27 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0011_delivery_outlet'),
    ]

    operations = [
        migrations.CreateModel(
            name='volunteerCoupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('serial_letter', models.CharField(default='A', max_length=1)),
                ('range_from', models.IntegerField(default=0)),
                ('range_to', models.IntegerField(default=0)),
                ('volunteer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
