# Generated by Django 4.1 on 2022-10-05 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0015_remove_source_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='volunteers.branch'),
        ),
    ]
