# Generated by Django 4.1 on 2022-10-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0017_alter_volunteers_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteers',
            name='status',
            field=models.CharField(default='pending_review', max_length=30),
        ),
    ]
